import {
  colorFamilies,
  motionScale,
  radiusScale,
  shadowScale,
  spacingScale,
  typographyScale,
} from "./foundations";

export const studioTheme = {
  background: colorFamilies.parchment[200],
  backgroundAlt: colorFamilies.parchment[300],
  surface: "rgba(251, 243, 229, 0.88)",
  surfaceStrong: "rgba(249, 238, 221, 0.95)",
  surfaceMuted: "#f0e3cb",
  ink: colorFamilies.slate[900],
  inkSoft: colorFamilies.slate[500],
  accent: colorFamilies.ember[600],
  accentSoft: colorFamilies.ember[400],
  border: "rgba(74, 56, 39, 0.22)",
  ok: colorFamilies.status.ok,
  warn: colorFamilies.status.warn,
  danger: colorFamilies.status.danger,
  info: colorFamilies.status.info,
  focusRing: "0 0 0 3px rgba(195, 140, 91, 0.28)",
} as const;

const spacingVars = Object.fromEntries(
  Object.entries(spacingScale).map(([key, value]) => [`--velum-space-${key}`, value]),
);

const radiusVars = Object.fromEntries(
  Object.entries(radiusScale).map(([key, value]) => [`--velum-radius-${key}`, value]),
);

export const designTokenVars: Record<string, string> = {
  ...spacingVars,
  ...radiusVars,
  "--velum-color-bg": studioTheme.background,
  "--velum-color-bg-alt": studioTheme.backgroundAlt,
  "--velum-color-surface": studioTheme.surface,
  "--velum-color-surface-strong": studioTheme.surfaceStrong,
  "--velum-color-surface-muted": studioTheme.surfaceMuted,
  "--velum-color-ink": studioTheme.ink,
  "--velum-color-ink-soft": studioTheme.inkSoft,
  "--velum-color-accent": studioTheme.accent,
  "--velum-color-accent-soft": studioTheme.accentSoft,
  "--velum-color-border": studioTheme.border,
  "--velum-color-ok": studioTheme.ok,
  "--velum-color-warn": studioTheme.warn,
  "--velum-color-danger": studioTheme.danger,
  "--velum-color-info": studioTheme.info,
  "--velum-focus-ring": studioTheme.focusRing,
  "--velum-font-body": typographyScale.body,
  "--velum-font-display": typographyScale.display,
  "--velum-font-mono": typographyScale.mono,
  "--velum-font-size-xs": typographyScale.size.xs,
  "--velum-font-size-sm": typographyScale.size.sm,
  "--velum-font-size-md": typographyScale.size.md,
  "--velum-font-size-lg": typographyScale.size.lg,
  "--velum-font-size-xl": typographyScale.size.xl,
  "--velum-font-size-hero": typographyScale.size.hero,
  "--velum-font-tracking-tight": typographyScale.tracking.tight,
  "--velum-font-tracking-normal": typographyScale.tracking.normal,
  "--velum-font-tracking-loud": typographyScale.tracking.loud,
  "--velum-motion-quick": motionScale.quick,
  "--velum-motion-base": motionScale.base,
  "--velum-motion-slow": motionScale.slow,
  "--velum-motion-ease-standard": motionScale.easing.standard,
  "--velum-motion-ease-decelerate": motionScale.easing.decelerate,
  "--velum-shadow-soft": shadowScale.soft,
  "--velum-shadow-lift": shadowScale.lift,
  "--velum-shadow-inset-accent": shadowScale.insetAccent,
  "--bg": studioTheme.background,
  "--bg-alt": studioTheme.backgroundAlt,
  "--ink": studioTheme.ink,
  "--ink-soft": studioTheme.inkSoft,
  "--accent": studioTheme.accent,
  "--accent-soft": studioTheme.accentSoft,
  "--surface": studioTheme.surface,
  "--surface-strong": studioTheme.surfaceStrong,
  "--surface-muted": studioTheme.surfaceMuted,
  "--border": studioTheme.border,
  "--ok": studioTheme.ok,
  "--warn": studioTheme.warn,
};

export const designTokens = {
  colorFamilies,
  spacingScale,
  radiusScale,
  typographyScale,
  motionScale,
  shadowScale,
  theme: studioTheme,
} as const;
