graph TD
classDef pantheon_children_of_the_moeders fill:#f6c3c0,stroke:#3b3b3b,stroke-width:1px;
classDef pantheon_church_of_omnis fill:#c4e3e0,stroke:#3b3b3b,stroke-width:1px;
classDef pantheon_huruma_s_offspring fill:#f3d2a3,stroke:#3b3b3b,stroke-width:1px;
classDef pantheon_moeders fill:#cbd7f2,stroke:#3b3b3b,stroke-width:1px;
classDef pantheon_vizira_s_offspring fill:#d7c3f6,stroke:#3b3b3b,stroke-width:1px;
classDef pantheon_zars_offspring fill:#f0e3b0,stroke:#3b3b3b,stroke-width:1px;
classDef pantheon_nan fill:#b9e2c8,stroke:#3b3b3b,stroke-width:1px;
subgraph group_infinite_loom["The Infinite loom"]
  direction LR
  subgraph group_major_rings["Major Rings"]
    direction LR
    subgraph group_core_realms["Core Realms"]
      direction LR
      subgraph stack_consciousness["Consciousness"]
        direction TB
        subgraph plane_the_murmuring_depths["The Murmuring Depths"]
          deity_damarus["Damarus<Br>nan"]
          class deity_damarus pantheon_moeders
          deity_morokei["Morokei<Br>nan"]
          class deity_morokei pantheon_moeders
          deity_agramon["Agramon<Br>nan"]
          class deity_agramon pantheon_children_of_the_moeders
          deity_gaberal["Gaberal<Br>God-That-Could-Die, The Frail God"]
          class deity_gaberal pantheon_vizira_s_offspring
          deity_daranthes["Daranthes<Br>The Trickster, The Traiterous"]
          class deity_daranthes pantheon_nan
          deity_quinglong["Quinglong<Br>God of all Dragons, Supreme Dragon"]
          class deity_quinglong pantheon_nan
        end
        subgraph plane_the_dreamscape["The Dreamscape"]
          deity_somnio["Somnio<Br>Deity of Dreams"]
          class deity_somnio pantheon_nan
          deity_ole_lokoje["Ole Lokoje<Br>King of Dunes"]
          class deity_ole_lokoje pantheon_nan
        end
        subgraph plane_the_throne_of_ambitions["The Throne of Ambitions"]
          deity_huruma["Huruma<Br>nan"]
          class deity_huruma pantheon_children_of_the_moeders
          deity_callista["Callista<Br>nan"]
          class deity_callista pantheon_huruma_s_offspring
          deity_roma["Roma<Br>nan"]
          class deity_roma pantheon_huruma_s_offspring
          deity_ophelia["Ophelia<Br>Goddess of Music"]
          class deity_ophelia pantheon_huruma_s_offspring
          deity_auctorion["Auctorion<Br>God of Authority, The Crowned Will, Sovereign of Ambition"]
          class deity_auctorion pantheon_nan
        end
      end
      subgraph plane_the_veil["The Veil"]
        deity_caprico["Caprico<Br>Guardian of Times, Ram of While"]
        class deity_caprico pantheon_nan
        deity_the_keywright["The Keywright<Br>Lord of Keys, The Master of Doors"]
        class deity_the_keywright pantheon_nan
        deity_alcmeon["Alcmeon<Br>Veilen Vagrant, The Captain of the Veil, The Vagabond"]
        class deity_alcmeon pantheon_nan
        deity_malkuth["Malkuth<Br>Patroller of Comsos, The Voyager, The Vagrant God"]
        class deity_malkuth pantheon_nan
        subgraph plane_orimond["Orimond"]
          deity_willebrand["Willebrand<Br>nan"]
          class deity_willebrand pantheon_zars_offspring
          deity_tybula["Tybula<Br>nan"]
          class deity_tybula pantheon_zars_offspring
          deity_zebulon["Zebulon<Br>nan"]
          class deity_zebulon pantheon_zars_offspring
          deity_vertugadin["Vertugadin<Br>Truth Speaker"]
          class deity_vertugadin pantheon_nan
          deity_verdugo["Verdugo<Br>Patron of Lies"]
          class deity_verdugo pantheon_nan
          deity_the_ocato["The Ocato<Br>God of the Flame"]
          class deity_the_ocato pantheon_nan
          deity_the_malocato["The Malocato<Br>Messiah of the Flame"]
          class deity_the_malocato pantheon_nan
          deity_yagnar["Yagnar<Br>Divine Champion of the Orcs"]
          class deity_yagnar pantheon_nan
          deity_dunavald["Dunavald<Br>Primordial Titan"]
          class deity_dunavald pantheon_nan
          deity_dunhark["Dunhark<Br>Primordial Titan"]
          class deity_dunhark pantheon_nan
          deity_jasandoril["Jasandoril<Br>God in a Bottle, The Weak, The Wishbearer"]
          class deity_jasandoril pantheon_nan
          deity_hase["Hase<Br>Queen of the Sky, Flight Maiden, The Skyborn"]
          class deity_hase pantheon_nan
          deity_nerion["Nerion<Br>Master of Sea and Storms, Guardian of the Seas"]
          class deity_nerion pantheon_nan
        end
      end
    end
    subgraph group_pull_of_light["Pull of light"]
      subgraph plane_everbright["Everbright"]
        deity_canuk["Canuk<Br>The Librarian, The Cornuto"]
        class deity_canuk pantheon_nan
      end
      subgraph plane_the_blinding_ends["The Blinding Ends"]
        deity_gate_of_truth["Gate of Truth<Br>Omniscience, Gizy ao zrfzm, Sal si hwiack, Git shaf trratsh, Gaave ro avruavh, Videnn de' aster, Edhekal eron nakhum"]
        class deity_gate_of_truth pantheon_nan
        deity_n_m_istam["Nòm istam<Br>The First Light, The Blinding One, Prima Lumin"]
        class deity_n_m_istam pantheon_nan
      end
      subgraph plane_the_kindling_plains["The Kindling Plains"]
        deity_yelna_of_the_light["Yelna of the Light<Br>The First of the Light, The Lightbearer, The Ancestor, The Aesterdawn"]
        class deity_yelna_of_the_light pantheon_nan
        deity_ragna_of_the_light["Ragna of the Light<Br>The Second of the Light, The Martyr of Light"]
        class deity_ragna_of_the_light pantheon_nan
      end
    end
    subgraph group_pull_of_shadow["Pull of Shadow"]
      subgraph plane_the_unraveling_ends["The Unraveling Ends"]
        deity_erebus["Erebus<Br>The Darkness, Ruler of the Unraveling"]
        class deity_erebus pantheon_nan
      end
      subgraph plane_the_unwaking_plains["The Unwaking Plains"]
        deity_quirmizi["Quirmizi<Br>God of Orcs"]
        class deity_quirmizi pantheon_nan
        deity_voskalel["Voskalel<Br>Golden Wyvern, Wigned Gold"]
        class deity_voskalel pantheon_nan
        deity_ova["Ova<Br>Wish Granter"]
        class deity_ova pantheon_nan
        deity_dunamedall["Dunamedall<Br>Warden of All Prison, Bane of the Oppressor"]
        class deity_dunamedall pantheon_nan
      end
    end
  end
  deity_omnis["Omnis<Br>Conscious Universe"]
  class deity_omnis pantheon_church_of_omnis
  deity_cassian["Cassian<Br>First Reaper"]
  class deity_cassian pantheon_nan
  deity_lazaro["Lazaro<Br>Third Reaper"]
  class deity_lazaro pantheon_nan
  deity_corvin["Corvin<Br>Second Reaper"]
  class deity_corvin pantheon_nan
  deity_the_legislator["The Legislator<Br>Ruler of Benevolence"]
  class deity_the_legislator pantheon_church_of_omnis
  deity_the_justificator["The Justificator<Br>Ruler of Malevolence"]
  class deity_the_justificator pantheon_church_of_omnis
  deity_the_weaver["The Weaver<Br>Weaver of Reality"]
  class deity_the_weaver pantheon_church_of_omnis
  deity_the_architect["The Architect<Br>Pillar of Existence"]
  class deity_the_architect pantheon_church_of_omnis
  subgraph plane_morena_s_realm["Morena's Realm"]
    deity_morena["Morena<Br>Whisperer of Death, Deadfather"]
    class deity_morena pantheon_nan
  end
  subgraph plane_the_domain_of_torment["The Domain of Torment"]
    deity_zars["Zars<Br>nan"]
    class deity_zars pantheon_children_of_the_moeders
    deity_sarruinn["Sarruinn<Br>God of Greed, Mordinfather, The Covetous Maw"]
    class deity_sarruinn pantheon_vizira_s_offspring
    deity_dun["Dun<Br>First Titan"]
    class deity_dun pantheon_nan
    deity_varec["Varec<Br>Hunter of Demons"]
    class deity_varec pantheon_nan
    deity_quercus["Quercus<Br>Patron of Murders, Saint-Quercus, The Patriarch"]
    class deity_quercus pantheon_nan
    deity_unmada["Unmada<Br>The Mad God, The Unhinged"]
    class deity_unmada pantheon_nan
  end
  subgraph plane_the_lithic_bastion["The Lithic Bastion"]
    deity_dravemir["Dravemir<Br>Hero of the Dwarf"]
    class deity_dravemir pantheon_nan
    deity_druquenein["Druquenein<Br>Harbinger of the Dwarves"]
    class deity_druquenein pantheon_nan
    deity_tiqyzeus["Tiqyzeus<Br>God of Blacksmiths, God of Artisan, The Creator, The One that Echoes in the Distance"]
    class deity_tiqyzeus pantheon_nan
    deity_liod["Liod<Br>Patron of Winter, The Cold Embrace"]
    class deity_liod pantheon_nan
    deity_scaphandria["Scaphandria<Br>God of the Deep"]
    class deity_scaphandria pantheon_nan
    deity_azromar["Azromar<Br>The Deep Crown, Lord of the Unyielding Heart"]
    class deity_azromar pantheon_nan
  end
  subgraph plane_the_realm_of_absolutism["The Realm of Absolutism"]
    deity_the_ordinator["The Ordinator<Br>Governor of Logics, The Absolute, Simetricus"]
    class deity_the_ordinator pantheon_huruma_s_offspring
  end
  subgraph plane_the_verdant_cradle["The Verdant Cradle"]
    deity_v_a["Véa<Br>nan"]
    class deity_v_a pantheon_nan
    deity_luthgarde["Luthgarde<Br>Protectress of the Woods,"]
    class deity_luthgarde pantheon_vizira_s_offspring
    deity_ratheithiae["Ratheithiae<Br>Primal Sun"]
    class deity_ratheithiae pantheon_nan
    deity_artume["Artume<Br>The Cunning Fox"]
    class deity_artume pantheon_nan
    deity_lirathiel["Lirathiel<Br>Queen of the Court of Broken Hearts"]
    class deity_lirathiel pantheon_nan
    deity_rakadishna["Rakadishna<Br>Goddess of Agriculture, The Fertile Princess"]
    class deity_rakadishna pantheon_nan
  end
  subgraph plane_the_void["The Void"]
    deity_the_voidress["The Voidress<Br>Queen of Nothing, The Derelict, The Forgotten Lover"]
    class deity_the_voidress pantheon_nan
  end
  subgraph plane_the_withered_womb["The Withered Womb"]
    deity_ezhoxorh["Ezhoxorh<Br>God of Plagues"]
    class deity_ezhoxorh pantheon_nan
    deity_zerecilda["Zerecilda<Br>Goddess of the Swarm"]
    class deity_zerecilda pantheon_nan
    deity_sepsurion["Sepsurion<Br>The Blightfather, He Who Feeds in Silence, The Rot That Remains, The Pale Bloom"]
    class deity_sepsurion pantheon_nan
  end
  subgraph plane_nan["nan"]
    deity_okoma["Okoma<Br>nan"]
    class deity_okoma pantheon_zars_offspring
  end
end
style group_infinite_loom fill:#f2e8dc,stroke:#555555,color:#000000;
style group_major_rings fill:#e2f0e9,stroke:#555555,color:#000000;
style group_core_realms fill:#e8e6f7,stroke:#555555,color:#000000;
style group_pull_of_light fill:#f7e6ef,stroke:#555555,color:#000000;
style group_pull_of_shadow fill:#f2f0d6,stroke:#555555,color:#000000;
style stack_life fill:#f2e8dc,stroke:#555555,color:#000000;
style stack_consciousness fill:#e2f0e9,stroke:#555555,color:#000000;
subgraph plane_the_far_cosmos["The Far Cosmos"]
  deity_bhaz_qorith["Bhaz’qorith<Br>nan"]
  class deity_bhaz_qorith pantheon_nan
  deity_c_thithr_zho["C'thithr'zho<Br>nan"]
  class deity_c_thithr_zho pantheon_nan
  deity_abhaaldrac["Abhaaldrac<Br>nan"]
  class deity_abhaaldrac pantheon_nan
end
subgraph plane_the_tesseral_leys["The Tesseral Leys"]
  deity_vizira["Vizira<Br>nan"]
  class deity_vizira pantheon_children_of_the_moeders
  deity_quillin["Quillin<Br>Administrator of the Sanctum, Tesseral Archon"]
  class deity_quillin pantheon_vizira_s_offspring
end
  deity_bhaz_qorith --> deity_v_a
  deity_c_thithr_zho --> deity_dunamedall
  deity_abhaaldrac --> deity_erebus
  deity_abhaaldrac --> deity_alcmeon
  deity_abhaaldrac --> deity_malkuth
  deity_morokei --> deity_damarus
  deity_huruma --> deity_damarus
  deity_huruma --> deity_morokei
  deity_vizira --> deity_damarus
  deity_vizira --> deity_morokei
  deity_vizira --> deity_the_weaver
  deity_zars --> deity_damarus
  deity_zars --> deity_morokei
  deity_agramon --> deity_damarus
  deity_agramon --> deity_morokei
  deity_okoma --> deity_zars
  deity_okoma --> deity_agramon
  deity_willebrand --> deity_zars
  deity_willebrand --> deity_agramon
  deity_tybula --> deity_zars
  deity_tybula --> deity_agramon
  deity_tybula --> deity_zebulon
  deity_zebulon --> deity_zars
  deity_zebulon --> deity_agramon
  deity_zebulon --> deity_tybula
  deity_callista --> deity_huruma
  deity_callista --> deity_agramon
  deity_roma --> deity_huruma
  deity_roma --> deity_agramon
  deity_ophelia --> deity_huruma
  deity_ophelia --> deity_agramon
  deity_ophelia --> deity_somnio
  deity_the_ordinator --> deity_huruma
  deity_the_ordinator --> deity_agramon
  deity_quillin --> deity_vizira
  deity_quillin --> deity_agramon
  deity_gaberal --> deity_vizira
  deity_gaberal --> deity_agramon
  deity_luthgarde --> deity_vizira
  deity_luthgarde --> deity_agramon
  deity_sarruinn --> deity_vizira
  deity_sarruinn --> deity_agramon
  deity_vertugadin --> deity_gate_of_truth
  deity_verdugo --> deity_vertugadin
  deity_verdugo --> deity_gate_of_truth
  deity_gate_of_truth --> deity_vertugadin
  deity_the_ocato --> deity_ratheithiae
  deity_the_ocato --> deity_daranthes
  deity_the_malocato --> deity_the_ocato
  deity_daranthes --> deity_vertugadin
  deity_daranthes --> deity_verdugo
  deity_daranthes --> deity_ratheithiae
  deity_yagnar --> deity_dunavald
  deity_yagnar --> deity_dunhark
  deity_quirmizi --> deity_yagnar
  deity_quirmizi --> deity_dun
  deity_quirmizi --> deity_dunavald
  deity_quirmizi --> deity_dunhark
  deity_dun --> deity_dunavald
  deity_dun --> deity_dunhark
  deity_dunavald --> deity_dun
  deity_dunhark --> deity_dun
  deity_dunhark --> deity_dunavald
  deity_dravemir --> deity_druquenein
  deity_druquenein --> deity_dravemir
  deity_varec --> deity_the_voidress
  deity_varec --> deity_quercus
  deity_dunamedall --> deity_quirmizi
  deity_artume --> deity_lirathiel
  deity_artume --> deity_liod
  deity_lirathiel --> deity_artume
  deity_lirathiel --> deity_liod
  deity_rakadishna --> deity_artume
  deity_jasandoril --> deity_varec
  deity_canuk --> deity_roma
  deity_canuk --> deity_quillin
  deity_liod --> deity_artume
  deity_liod --> deity_lirathiel
  deity_hase --> deity_luthgarde
  deity_hase --> deity_nerion
  deity_zerecilda --> deity_ezhoxorh
  deity_the_legislator --> deity_omnis
  deity_the_justificator --> deity_omnis
  deity_the_justificator --> deity_the_legislator
  deity_the_weaver --> deity_omnis
  deity_the_architect --> deity_omnis
  deity_the_architect --> deity_the_legislator
  deity_the_architect --> deity_the_weaver
